package com.example.mishkat_world.allhistory;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.widget.AdapterView;
import android.widget.Button;
import android.widget.TextSwitcher;
import android.widget.TextView;
import android.widget.ViewSwitcher;
import com.example.mishkat_world.allhistory.Adaptor.MovieAdaptor;
import com.example.mishkat_world.allhistory.Common.Common;
import com.example.mishkat_world.allhistory.Model.Movie;
import it.moondroid.coverflow.components.ui.containers.FeatureCoverFlow;

public class MainActivity extends AppCompatActivity {



    FeatureCoverFlow coverFlow;
    MovieAdaptor adaptor;
    TextSwitcher mTitle;
    Button btn;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Intent intent = getIntent();

        initData();
        adaptor = new MovieAdaptor(Common.movieList,this);
        coverFlow = (FeatureCoverFlow)findViewById(R.id.coverFlow);
        mTitle= (TextSwitcher)findViewById(R.id.mtitle);
        mTitle.setFactory(new ViewSwitcher.ViewFactory() {
            @Override
            public View makeView() {
                LayoutInflater inflater = LayoutInflater.from(MainActivity.this);
                TextView text = (TextView)inflater.inflate(R.layout.layout_title,null);
                return text;
            }
        });
        coverFlow.setAdapter(adaptor);
        coverFlow.setOnScrollPositionListener(new FeatureCoverFlow.OnScrollPositionListener() {
            @Override
            public void onScrolledToPosition(int position) {
                mTitle.setText(Common.movieList.get(position).getTitle());
            }

            @Override
            public void onScrolling() {

            }
        });
        coverFlow.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                Intent intent = new Intent(MainActivity.this,MovieDetail.class);
                intent.putExtra("movie_index",position);
                startActivity(intent);
            }
        });

        Button btn = (Button)findViewById(R.id.btn);
        btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent1 = new Intent(MainActivity.this,More.class);
                startActivity(intent1);
            }
        });



    }

    private void initData() {

        Movie movie = new Movie("The Shawshank Redemption", "Andy Dufresne (Tim Robbins) is sentenced to two consecutive life terms in prison for the murders of his wife and her lover and is sentenced to a tough prison. However, only Andy knows he didn't commit the crimes. While there, he forms a friendship with Red (Morgan Freeman), experiences brutality of prison life, adapts, helps the warden, etc., all in 19 years."
        ,"https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg");
        Common.movieList.add(movie);
         movie = new Movie("The God Father", "Widely regarded as one of the greatest films of all time, this mob drama, based on Mario Puzo's novel of the same name, focuses on the powerful Italian-American crime family of Don Vito Corleone (Marlon Brando). When the don's youngest son, Michael (Al Pacino), reluctantly joins the Mafia, he becomes involved in the inevitable cycle of violence and betrayal. Although Michael tries to maintain a normal relationship with his wife, Kay (Diane Keaton), he is drawn deeper into the family business.",
                 "https://upload.wikimedia.org/wikipedia/en/thumb/a/af/The_Godfather%2C_The_Game.jpg/220px-The_Godfather%2C_The_Game.jpg");
        Common.movieList.add(movie);

        Common.movieList.add(new Movie("Steve Jobs","Steven Paul Jobs was an American inventor, designer and entrepreneur who was the co-founder, chief executive and chairman of Apple Computer. Apple's revolutionary products, which include the iPod, iPhone and iPad, are now seen as dictating the evolution of modern technology. Born in 1955 to two University of Wisconsin graduate students who gave him up for adoption, Jobs was smart but directionless, dropping out of college and experimenting with different pursuits before co-founding Apple with Steve Wozniak in 1976. Jobs left the company in 1985, launching Pixar Animation Studios, then returned to Apple more than a decade later. Jobs died in 2011 following a long battle with pancreatic cancer.",
                "https://naqyr37xcg93tizq734pqsx1-wpengine.netdna-ssl.com/wp-content/uploads/2017/11/10-Things-We-Can-Learn-From-the-Incredible-Steve-Jobs.jpg"));

        Common.movieList.add(new Movie("Luis Alvarez", "Lived 1911 – 1988.\n" +
                "Luis Alvarez was a Nobel Prize winning physicist, probably most famous for the discovery of the iridium layer and his theory that the mass extinction of dinosaurs was caused by an asteroid or comet colliding with Earth. Besides doing the normal work you might expect of a physics professor, Alvarez took on more unusual projects, like making use of cosmic rays to search for hidden chambers in an Egyptian pyramid.", "https://www.nobelprize.org/images/alvarez-13206-content-portrait-mobile-tiny.jpg"));
        Common.movieList.add(new Movie("Archimedes","Archimedes was born in the Greek city-state of Syracuse on the island of Sicily in approximately 287 BC. His father, Phidias, was an astronomer. Archimedes was, arguably, the world’s greatest scientist – certainly the greatest scientist of the classical age.\n" +
                "\n" +
                "He was a mathematician, physicist, astronomer, engineer, inventor, and weapons-designer. As we’ll see, he was a man who was both of his time and far ahead of his time.","http://biozvezd.ru/images/45/45244/stesihor.jpg"));

        Common.movieList.add(new Movie("Aristotle ","Lived 384 – 322 BC.\n" +
                "Aristotle’s influence on western culture and science has been enormous. His writings, many of which survived great periods of turmoil in the millennia separating us from him, show him to be a man of tremendous intellect who thought deeply about the world.\n" +
                "\n" +
                "The volume, extent and depth of his work is humbling.\n" +
                "\n" +
                "Speaking from our privileged place in time, it is evident that much of his work actually weakened the progress of science. There are, however, exceptions to this: for example, some of his works on biology and geology. He also founded the study of formal logic.","https://www.famousscientists.org/images1/aristotle.jpg"));
        Common.movieList.add(new Movie("Amedeo Avogadro ","Lived 1776 – 1856.\n" +
                "Amedeo Avogadro is best known for his hypothesis that equal volumes of different gases contain an equal number of molecules, provided they are at the same temperature and pressure.\n" +
                "\n" +
                "His hypothesis was rejected by other scientists. It only gained acceptance after his death. It is now called Avogadro’s law.\n" +
                "\n" +
                "Avogadro was also the first scientist to realize that elements could exist in the form of molecules rather than as individual atoms.","https://www.famousscientists.org/fs/wp-content/uploads/2014/12/amedeo-avogadro.png"));
        Common.movieList.add(new Movie("Alexander Graham Bell","(Born March 3, 1847, Edinburgh, Scotland—died August 2, 1922, Beinn Bhreagh, Cape Breton Island, Nova Scotia, Canada), Scottish-born American inventor, scientist, and teacher of the deaf whose foremost accomplishments were the invention of the telephone (1876) and the refinement of the phonograph (1886).","https://www.biography.com/.image/t_share/MTIwNjA4NjMzNzM5ODM4OTg4/alexander-graham-bell-9205497-2-402.jpg"));
        Common.movieList.add(new Movie("Niels Bohr","Lived 1885 – 1962.\n" +
                "Niels Bohr completely transformed our view of the atom and of the world. Realizing that classical physics fails catastrophically when things are atom-sized or smaller, he remodeled the atom so electrons occupied ‘allowed’ orbits around the nucleus while all other orbits were forbidden. In doing so he founded quantum mechanics.\n" +
                "\n" +
                "Later, as a leading architect of the Copenhagen interpretation of quantum mechanics, he helped to reshape our understanding of how nature operates at the atomic scale.","https://www.famousscientists.org/images1/niels-bohr.jpg"));

        Common.movieList.add(new Movie("Isaac Newton","Lived 1643 to 1727.\n" +
                "Isaac Newton is perhaps the greatest physicist who has ever lived. He and Albert Einstein are almost equally matched contenders for this title.\n" +
                "\n" +
                "Each of these great scientists produced dramatic and startling transformations in the physical laws we believe our universe obeys, changing the way we understand and relate to the world around us.","https://www.famousscientists.org/images1/isaac-newton.png"));
        Common.movieList.add(new Movie("Alfred Nobel","Lived 1833 – 1896.\n" +
                "Alfred Nobel is famous for the annual prizes in science, literature, and peace awarded in his name.\n" +
                "\n" +
                "Although he was born into poverty, his family members were creative and entrepreneurial; they worked hard and became successful. Alfred was the scientist of the family, inventing and manufacturing dynamite, the blasting cap, gelignite, and ballistite. He grew fantastically rich on the proceeds of his explosives businesses.\n" +
                "\n" +
                "In his last will and testament, he bequeathed over ninety percent of his fortune to fund the Nobel Prizes.","https://www.famousscientists.org/images1/alfred-nobel.jpg"));

        Common.movieList.add(new Movie("J. J. Thomson","Lived 1856 – 1940.\n" +
                "J. J. Thomson took science to new heights with his 1897 discovery of the electron – the first subatomic particle.\n" +
                "\n" +
                "He also found the first evidence that stable elements can exist as isotopes and invented one of the most powerful tools in analytical chemistry – the mass spectrometer.","https://www.famousscientists.org/images1/j-j-thomson.jpg"));
        Common.movieList.add(new Movie("Jagdish Chandra Bose","Sir Jagadish Chandra Bose is one of the most prominent first Indian scientists who proved by experimentation that both animals and plants share much in common. He demonstrated that plants are also sensitive to heat, cold, light, noise and various other external stimuli. Bose contrived a very sophisticated instrument called the crescograph, which could record and observe plants minute responses to external stimulants. It was capable of magnifying the motion of plant tissues to about 10,000 times of their actual size and, in doing so, found many similarities between plants and other living organisms.","https://siliweb-45drr7xgfrlalqxntz.netdna-ssl.com/current/wp-content/uploads/2016/12/PAGE-ASH-BOSE-01-SLIDER.jpg"));
        Common.movieList.add(new Movie("Elon Musk ","Elon Reeve Musk (born June 28, 1971) is a South African-born American entrepreneur and businessman who founded X.com in 1999 (which later became PayPal), SpaceX in 2002 and Tesla Motors in 2003. Musk became a multimillionaire in his late 20s when he sold his start-up company, Zip2, to a division of Compaq Computers. Musk made headlines in May 2012, when SpaceX launched a rocket that would send the first commercial vehicle to the International Space Station. ","https://astrumpeople.com/wp-content/uploads/2015/02/Elon-Musk-e1425245632245.jpg"));
        Common.movieList.add(new Movie("Larry Page ","Lawrence Edward Page[5] (born March 26, 1973) is an American computer scientist and Internet entrepreneur who co-founded Google with Sergey Brin.[1][6]\n" +
                "\n" +
                "Page is the chief executive officer of Alphabet Inc. (Google's parent company). After stepping aside as Google CEO in August 2001, in favor of Eric Schmidt, he re-assumed the role in April 2011. He announced his intention to step aside a second time in July 2015, to become CEO of Alphabet, under which Google's assets would be reorganized. Under Page, Alphabet is seeking to deliver major advancements in a variety of industries.[7]\n" +
                "\n" +
                "As of October 2018, Page was the 9th-richest person in the world, with a net worth of $53.4 billion.[8]","https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Larry_Page_in_the_European_Parliament%2C_17.06.2009_%28cropped%29.jpg/220px-Larry_Page_in_the_European_Parliament%2C_17.06.2009_%28cropped%29.jpg"));
        Common.movieList.add(new Movie("Carl Sassenrath","Carl Sassenrath (born 1957 in California) is an architect of operating systems and computer languages. He brought multitasking to personal computers in 1985 with the creation of the Amiga Computer operating system kernel, and he is the designer of the REBOL computer language, REBOL/IOS collaboration environment, the Safeworlds AltME private messaging system, and other products. Carl is currently a Principal Engineer at Roku, Inc.","https://upload.wikimedia.org/wikipedia/commons/3/3f/Carl-sassenrath-04.jpg"));
        Common.movieList.add(new Movie("Guido van Rossum","Guido van Rossum ( born 31 January 1956) is a Dutch programmer best known as the author of the Python programming language, for which he was the \"Benevolent dictator for life\" (BDFL) until he stepped down from the position in July 2018.","https://pbs.twimg.com/profile_images/424495004/GuidoAvatar_400x400.jpg"));
        Common.movieList.add(new Movie("Mark Zuckerburg "," Born on May 14, 1984, in White Plains, New York, Mark Zuckerberg co-founded the social-networking website Facebook out of his college dorm room. He left Harvard after his sophomore year to concentrate on the site, the user base of which has grown to more than 2 billion people, making Zuckerberg a billionaire.","http://www.gstatic.com/tv/thumb/persons/589228/589228_v9_ba.jpg"));
        Common.movieList.add(new Movie("Brendan Eich","Brendan Eich ( born July 4, 1961) is an American technologist and creator of the JavaScript programming language. He co-founded the Mozilla project,[2] the Mozilla Foundation and the Mozilla Corporation, and served as the Mozilla Corporation's chief technical officer and briefly its chief executive officer.He is the CEO of Brave Software","https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Brendan_Eich_Mozilla_Foundation_official_photo.jpg/220px-Brendan_Eich_Mozilla_Foundation_official_photo.jpg"));
        Common.movieList.add(new Movie("Bill Gates ","Entrepreneur and businessman Bill Gates (born October 28, 1955) and his partner Paul Allen founded and built the world's largest software business, Microsoft, through technological innovation, keen business strategy and aggressive business tactics. In the process, Gates became one of the richest men in the world.","http://www.gstatic.com/tv/thumb/persons/614/614_v9_bc.jpg"));
        Common.movieList.add(new Movie("Sergey Mikhaylovich Brin ","Sergey Mikhaylovich Brin ( born August 21, 1973) is an American computer scientist and internet entrepreneur. Together with Larry Page, he co-founded Google. Brin is the President of Google's parent company Alphabet Inc. As of October 2018, Brin is the 13th-richest person in the world, with an estimated net worth of US$50.6 billion.","https://amp.businessinsider.com/images/59cbc8e9c68d7b6d118b4922-750-563.jpg"));
        Common.movieList.add(new Movie("Abraham Lincoln ","Abraham Lincoln was an American statesman and lawyer who served as the 16th President of the United States from March 1861 until his assassination in April 1865. Lincoln led the United States through the American Civil War—its bloodiest war and perhaps its greatest moral, constitutional, and political crisis.","https://www.biographyonline.net/images/150/250-Abraham_Lincoln.jpg"));

        Common.movieList.add(new Movie("Martin Luther King","Martin Luther King Jr was one of America’s most influential civil rights activists. His passionate, but non-violent protests, helped to raise awareness of racial inequalities in America, leading to significant political change. Martin Luther King was also an eloquent orator who captured the imagination and hearts of people, both black and white.","https://www.biographyonline.net/wp-content/uploads/2014/05/Martin_Luther_King_Jr2.jpg"));
        Common.movieList.add(new Movie(" Nelson Mandela","Nelson Mandela (1918 – 2013) was a South African political activist who spent over 20 years in prison for his opposition to the apartheid regime; he was released in 1990. In 1994, Mandela was later elected the first leader of a democratic South Africa. He was awarded the Nobel Peace Prize (jointly with F.W. de Klerk) in 1993 for his work in helping to end racial segregation in South Africa. He is considered the father of a democratic South Africa and widely admired for his ability to bring together a nation, previously divided by apartheid. Nelson Mandela is one of the most admired political leaders of the Twentieth and Twenty-First Century for his vision to forgive and forge a new ‘rainbow’ nation.","https://www.biographyonline.net/wp-content/uploads/2014/05/mandela-2151.jpg"));
        Common.movieList.add(new Movie("Queen Elizabeth II ","Queen Elizabeth (1952 – ) was crowned Head of State, Head of the Commonwealth and Supreme Governor of the Church of England in 1952.\n" +
                "\n" +
                "She is the longest-serving British monarch and has presided over half a century of continual change both within the Royal Family, Great Britain and the Commonwealth.","https://www.biographyonline.net/wp-content/uploads/2014/05/Elizabeth_II2.jpg"));
        Common.movieList.add(new Movie("Muhammad Ali","Muhammad Ali (born Cassius Marcellus Clay, Jr. January 17, 1942 – 3 June 2016) was an Olympic and World Champion boxer, who also had a unique personality, based on self-belief and strong religious and political convictions.  In 1999, Ali was crowned “Sportsman of the Century” by Sports Illustrated. He won the World Heavyweight Boxing championship three times and won the North American Boxing Federation championship as well as an Olympic gold medal.","https://www.biographyonline.net/wp-content/uploads/2014/05/Muhammad_Ali22.jpg"));
        Common.movieList.add(new Movie("Mahatma Gandhi","Mahatma Gandhi was a prominent Indian political leader who campaigned for Indian independence. He employed non-violent principles and peaceful disobedience. He was assassinated in 1948, shortly after achieving his life goal of Indian independence. In India, he is known as ‘Father of the Nation’." , "https://www.biographyonline.net/images/150/200px-MKGandhi.jpg"));
        Common.movieList.add(new Movie("Sheikh Mujibur Rahman ","Sheikh Mujibur Rahman (Bengali: শেখ মুজিবুর রহমান); (17 March 1920 – 15 August 1975), shortened as Sheikh Mujib or just Mujib, was a Bengali politician and statesman. He is the founding father of the People's Republic of Bangladesh. He served as the first President of Bangladesh and later Prime Minister of Bangladesh from March 1971 until his assassination in August 1975. He is considered to be the driving force behind the independence of Bangladesh. He is popularly known under the title of Bangabandhu (Bôngobondhu \"Friend of Bengal\"). He became a leading figure in and eventually the leader of the Awami League, founded in 1949 as an East Pakistan-based political party in Pakistan. Mujib is credited as an important figure in efforts to gain politician autonomy for East Pakistan and later as the central figure behind the Bangladesh Liberation Movement and the Bangladesh Liberation War in 1971. Thus, he is regarded Jatir Janak or Jatir Pita (Jatir Jônok or Jatir Pita, both meaning \"Father of the Nation\") of Bangladesh. His daughter Sheikh Hasina is the current leader of the Awami League and the present Prime Minister of Bangladesh.","https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Sheikh_Mujibur_Rahman_in_1950.jpg/220px-Sheikh_Mujibur_Rahman_in_1950.jpg"));
        Common.movieList.add(new Movie("Queen Victoria","Queen Victoria was born 24 May 1819. She was the granddaughter of George III, and her father, Edward was fourth in line to the throne. But when the prince of Wales died early, his brothers sought to get married and maintain the line of succession. Edward married Princess Victoria from Germany, and the couple had just one child, Alexandrina Victoria, who was born at Kensington Palace in 1819. As a young girl, Victoria’s father died, followed six days later by King George III. The throne then passed to  King William IV, but, he too died early. This left Victoria to be crowned at the age of 18, in June 1837. Queen Victoria was to reign until her death on 22nd January 1901.","https://www.biographyonline.net/wp-content/uploads/2014/05/Queen_Victoria1.jpg"));
        Common.movieList.add(new Movie("Pope Francis","Pope Francis (Jorge Mario Bergoglio) was elected Pope of the Catholic Church in 2013, he took the name Francis after Saint Francis of Assisi, who was known for his embrace of poverty and chastity.Since his election, Pope Francis has stamped his own authority on the Church. In particular, he has sought to emphasize the traditional principles in the gospels of humility, charity and modesty. He has sought to encourage the church to place more emphasis on personal religious practise and concern for the poor, rather than issues related to abortion, contraception and homosexuality. He has personally rejected the more luxurious apartments in the Vatican, preferring to choose simple garments and live in more simple accommodation.","https://www.biographyonline.net/wp-content/uploads/2014/05/Pope_Francis2.jpg"));
        Common.movieList.add(new Movie("Leonardo da Vinci","Leonardo da Vinci (1452 – 1519) is one of the world’s greatest thinkers, artists and philosophers. Seeking after perfection, he created rare masterpieces of art such as ‘The Mona Lisa’ and The Last Supper.’\n" +
                "\n" +
                "In addition to art, Da Vinci studied all aspects of life from anatomy to mathematics and astronomy; his far-reaching investigations and discoveries sought to show an underlying unity of the universe. Da Vinci is considered to be a key person in the birth of the European Renaissance, which saw an emergence of new ideas, scientific discoveries and the creation of beautiful art.","https://www.biographyonline.net/images/150/250-leonardo-da-vinci.jpg"));
        Common.movieList.add(new Movie("Thomas Edison","Thomas Edison (1847 – 1931) was an American inventor and businessman who developed and made commercially available – many key inventions of modern life. His Edison Electric company was a pioneering company for delivering DC electricity directly into people’s homes. He filed over 1,000 patents for a variety of different inventions. Crucially, he used mass-produced techniques to make his inventions available at low cost to households across America. His most important inventions include, the electric light bulb, the phonograph, the motion picture camera, an electric car and the electric power station.","https://www.biographyonline.net/wp-content/uploads/2014/05/Thomas_Edison23.jpg"));
        Common.movieList.add(new Movie("Walt Disney","Walt Disney (1901 – 1966) was a film producer, media magnate and co-founder of the Walt Disney Company. He was an iconic figure in the Twentieth Century media and entertainment industry, helping to produce many films. With his staff, he created famous cartoon characters, such as Mickey Mouse and Donald Duck; his name was also used for the successful Disney Theme Parks. During his lifetime, he received a record 59 Nominations for the Academy Awards, winning 22 Awards.","https://www.biographyonline.net/wp-content/uploads/2014/05/Walt_disney2.jpg"));
        Common.movieList.add(new Movie("Neil Armstrong ","Neil Armstrong (1930 – 2012) was an American astronaut – who gained the distinction of being the first person to both land and walk on the moon.\n" +
                "\n" +
                "“That’s one small step for [a] man, one giant leap for mankind.”\n" +
                "\n" +
                "– Neil Armstrong (21 July 1969)\n" +
                "\n" +
                "Early life Neil Armstrong\n" +
                "Armstrong was born 5 August 1930 in Wapakoneta, Ohio, US. He attended Blue High School and took flying lessons while still a student; by the time he was 16, he had gained his flight certificate. Aged 17, he studied aeronautical engineering at Purdue University, turning down a chance to study at MIT. His studies were partly financed by the US Navy and, after his first two years, he was called up to the Navy for flight training, where he qualified to be a naval aviator.","https://www.biographyonline.net/wp-content/uploads/2015/02/Neil_Armstrong_pose.jpg"));
        Common.movieList.add(new Movie("J.K.Rowling","J.K Rowling was born in Chipping Sodbury, July 31st, 1965. Her childhood was generally happy, although she does remember getting teased because of her name, “Rowling” – She recalls often getting called “Rowling pin” by her less than ingenious school friends. J.K. Rowling says she never really warmed to her own name, although, she does remember having a fondness for the name Potter from quite an early age. J.K.Rowling studied at St Michael’s Primary School in Gloucestershire, before moving to Chepstow, South Wales at the age of nine.\n" +
                "\n" +
                "From an early age, J.K. Rowling had the ambition to be a writer. She often tried her hand at writing, although little came from her early efforts. Aged six she wrote a book about a rabbit with measles. After her mother praised her effort. Rowling replied ‘well get it published then.’ She admits it was a ‘Bit of an odd thing for a child of six to think. I don’t know where it came from…”\n" +
                "\n" +
                "In her own autobiography, she remembers with great fondness, when her good friend Sean became the first person to give her the confidence that one day she would be able to make a very good writer.","https://www.biographyonline.net/wp-content/uploads/2014/05/jk-rowling4.jpg"));
        Common.movieList.add(new Movie("Lionel Messi","Lionel Messi is an Argentinian footballer widely regarded as one of the greatest players of the modern generation. He plays for FC Barcelona and the Argentina national team. He has won FIFA world player of the year four times (a record already). He has often been described as Diego Maradona’s successor because of his prolific goal scoring record and ability to dribble past opponents.","https://pbs.twimg.com/media/Dgo2WEuX0AEo9IP.jpg"));
        Common.movieList.add(new Movie("Adolf Hitler","Adolf Hitler (1889-1945) was a charismatic leader of the Nazi party, gaining power in 1933 and become dictator of Germany until his death in 1945. He led Germany in an aggressive war of conquest invading Western Europe and then the Soviet Union. Initially successful, his army then suffered a series of reverses, before the eventual complete defeat of his Nazi Germany in 1945. Hitler has become infamous as a personification of human evil. His name is inexorably linked to the Holocaust and extermination of Jews and other ‘undesirables’. He is also seen as the principle cause of the Second World War in which over 70 million people died. Yet, in the midst of the Great Depression, he captivated a nation with his mixture of charm, xenophobia, and ability to persuade.","https://www.biographyonline.net/wp-content/uploads/2014/05/adolf-hitler-1501.jpg"));
        Common.movieList.add(new Movie("World War I","World War One (1914-1918) was once called the Great War. No one during that time could imagine anything worse. That is until they faced themselves with WWII and even more bloodshed. But WWI was not pushed aside. In fact, historian, George Kennan, said that all roads lead to WWI. In truth, Kennan was right on the money. WWII’s causes can be traced right back to WWI where so much was left undone and so much resentment and hatred brewed below the surface. It was the humiliation of Germany at the end of WWI that began the movement toward WWII. The hatred toward the world that many Germans felt led to the election of Hitler, the creation of concentration camps, and the fall of France, Poland, and many other countries. An unsatisfied closure to the Great War caused it to be the silence before the storm.","https://usercontent1.hubstatic.com/2885050_f520.jpg"));
        Common.movieList.add(new Movie("World War II","This is one of the few wars that literally involved most of the world. The scarring from this six-year fight is still seen today in the demolished buildings and the tattooed numbers on the arms of POWs. There was no one main objective or enemy. There was no main front. It was composed of the European, African, and Asian segments of the war. It ripped through every economic level, race, religion, and culture. Country after country fell into other hands. Men, women, and children were killed by the millions. Many lost their loved ones and had to seek new lands to call home as there was so much devastation. World War II also led to the creation of the United Nations, a homeland for the Jews, and the beginning of the Cold War. The world had changed and was never to return to the innocence it once claimed. It was the unmasking of an underlying evil that took an ugly shape in the Cold War. Only as the truth of the massacres, plots, and campaigns have revealed themselves has the world truly begun to heal.","https://usercontent2.hubstatic.com/2885021_f520.jpg"));
        Common.movieList.add(new Movie("The Life of Muhammad","Before Muhammad rose up as the founder of Islam, the Middle East was full of small tribes that warred against each other continuously. Muhammad brought those tribes together and gave them a purpose and a reason to join forces. Though blood was still shed, it was not against each other. It was against those that threatened the new religion or fought against it.\n" +
                "\n" +
                "After Muhammad brought together the Middle East, the region experienced the Islamic Golden Age from 786 to 1258 AD. This time is analogous to Europe's Renaissance (though during this time, Europe was still in the Dark Ages). The region's culture flourished and made many advances in fields including mathematics and science. The world benefited from Muslims' discovery of the immune system, preservation of Roman and Greek texts, and invention of the number zero, the decimal system, and algebra. Even coffee was discovered during the Islamic Golden Age! The stability Muhammad brought to the region was one of the reasons that the culture was able to make such advances.\n" +
                "\n" +
                "Since the birth of Islam, it has become one of the largest religions of the world. It covers the globe, and through many of its sects, it has influenced the world. The terrorist branches have reached out and impacted the daily lives of every person through their traveling procedures or just the way they go to work with extra security. Muhammad changed the shape of the Middle East that is still changing today.","https://usercontent2.hubstatic.com/2885083_f520.jpg"));
        Common.movieList.add(new Movie("Atomic bombings of Hiroshima and Nagasaki","In August 1945, during the final stage of the Second World War, the United States dropped atomic bombs on the Japanese cities of Hiroshima and Nagasaki. The two bombings, which killed at least 129,000 people, remain the only use of nuclear weapons for warfare in history. As the Second World War entered its sixth and final year, the Allies had begun to prepare for, what was anticipated to be, a very costly invasion of the Japanese mainland. This was preceded by an immensely destructive firebombing campaign that obliterated many Japanese cities. ","https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Atomic_bombing_of_Japan.jpg/1200px-Atomic_bombing_of_Japan.jpg"));
        Common.movieList.add(new Movie("Pearl Harbour Attacked","December 7th 1941 - The Imperial Japanese Navy launches a surprise devastating air attack against the United States naval base at Pearl Harbour, Hawaii","http://www.emlii.com/images/article/2014/04/5356b64a8f859.jpeg"));
        Common.movieList.add(new Movie("India and Pakistan Gain Independence ","Viscount Louis Mountbatten announced the partitioning of the British Indian Empire into India and Pakistan. Pakistan was then declared a separate nation from Britain on the 14 August 1947. On 15 August 1947, India became an independent nation.","http://www.emlii.com/images/article/2014/04/5356bd598c642.jpeg"));
        Common.movieList.add(new Movie(" 9/11 - A Day that Shook the World","On September 11, 2001 at 8.46am, American Airlines flight 11 crashed into the North tower of the World Trade Centre. It was the start of four coordinated suicide attacks on the USA. Nearly 3000 people died on that day. It became a day that changed the world.","http://www.emlii.com/images/article/2014/04/5356dba7e658f.jpeg"));
        Common.movieList.add(new Movie("Android","Android is a mobile operating system developed by Google, based on a modified version of the Linux kernel and other open source software and designed primarily for touchscreen mobile devices such as smartphones and tablets and it launched September 23, 2008.","https://www.android.com/static/2016/img/share/andy-lg.png"));
        Common.movieList.add(new Movie(" Walmart","Walmart has added e-commerce business to its thriving physical hypermarkets to top our list as the world’s richest company in terms of revenue. Its sheer size and deep pockets enable it to cut prices to attract more customers and take away market share from its main rivals Amazon and Target. Walmart operates e-commerce sites in 11 nations and 11,000 brick-and-mortar stores in 28 nations. Its headquarters is in Bentonville, Arkansas and the enterprise was founded in 1945.\n" +
                "\n" +
                "Walmart also owns Asda in the UK and employs more than 2.3 million workers globally including 1.5 million in the U S. Recently, the enterprise rewarded more than 200,000 employees with promotions and higher pay. It plans to invest more than $2.3 billion in better wages, education, and training to provide greater opportunities and rewards to its employees. Walmar is currently headed by CEO Doug McMillon.","https://s.financesonline.com/uploads/2018/03/Walmart-edited.jpg"));
        Common.movieList.add(new Movie("Toyota Motor","Toyota Motor is the world’s largest automotive maker and a leader in the hybrid electric car sector. It had sold more than 6 million units of its widely used Prius car by January 2017. Besides Toyota, other brands in the stable include Daihatsu, Ranz, Hino, and Lexus.\n" +
                "\n" +
                "Toyota was founded in 1937 and is headquartered in the city of Toyota in Japan’s Aichi region. The company employs more than 348,000 workers. Its current CEO is Akio Toyoda. Toyota is the first automobile company to make more than 12 million units in a year which it has accomplished since 2012. However, recently, it had to recall millions of vehicles twice due to faulty airbags. The company’s future plans include making driverless cars and expanding its presence in the hybrid electric vehicles market.","https://s.financesonline.com/uploads/2018/03/Toyota-Motor-edited.jpg"));
        Common.movieList.add(new Movie("Volkswagen ","Volkswagen is German for “people’s car”. The company was founded in 1937 by the German Labour Front under Adolf Hitler to make an affordable car for the masses, unlike luxury vehicles. Today, the company’s main markets are Germany and China. The Volkswagen Group is currently the world’s biggest automaker and controls top brands such as Skoda, MAN, Scania, Bugatti, Bentley, Lamborghini, SEAT, and Audi.\n" +
                "\n" +
                "Volkwagen is headquartered in Wolfsburg in Germany’s Lower Saxony region. The company makes buses, trucks, and cars, and employs more than 600,000 workers in its factories. Its current CEO is Matthias Muller. In 2015, a diesel scandal affected Volkswagen and the company lost revenue as it had to recall half a million cars. Volkswagen has to shell out $15.3 billion as compensation to purchasers of its impacted diesel cars in the US and in penalties to regulators.","https://s.financesonline.com/uploads/2018/03/Volkswagen-edited.jpg"));
        Common.movieList.add(new Movie("Royal Dutch Shell","Royal Dutch Shell, widely referred to as Shell, is among the six “supermajors” in the oil and gas industry. This company is involved in exploration, production, refining, marketing, distribution, power general, petrochemicals, and trading as well as in renewable energy fields like wind and biofuels. Shell produces around 3.7 million barrels of oil per day and runs business in more than 70 nations. It currently has the highest market cap on the London Stock Exchange and is also traded on the New York Stock Exchange.\n" +
                "\n" +
                "Shell was founded in 1907 and is headquartered in The Hague, Netherlands. It employs about 90,000 employees globally. The company’s current CEO is Ben van Beurden. In 2016, Shell spent $53 billion to acquire the BG group to become the world’s largest liquefied natural gas company. The acquisition gave Shell a dominant position in drilling in the prize location of offshore Brazil.","https://s.financesonline.com/uploads/2018/03/Royal-Dutch-Shell-edited.jpg"));
        Common.movieList.add(new Movie("Apple Inc.","Apple is currently the world’s most profitable publicly traded company. In the past decade, its sales have been driven by the popular iPod music player and the iPhone. However, of late, sales of the Apple Watch and iPad have gone down and the company relies heavily on upgraded phone models. It is exploring new opportunities in software and automobiles. Apple is based in Cupertino, California and was founded in 1977 by Steve Jobs, Ronald Wayne, and Steve Wozniak.\n" +
                "\n" +
                "Apple operates about 478 stores in 17 nations. Its popular products include Mac, Apple TV, Watch OS, and iOS. Apple is the world’s biggest technology enterprise by revenue and assets. It employs more than 110,000 people and is the second largest maker of mobile phones following Samsung. For the future, Apple has planned to focus on boosting its operations in India and entering the automobile sector with an electric model.","https://s.financesonline.com/uploads/2018/03/Apple-Inc-edited.jpg"));
        Common.movieList.add(new Movie(" Alibaba","China's largest e-commerce company is an absolute growth machine – and compound growth goes haywire when it's 30 to 60 percent annually over a handful of years. Alibaba revenue soared from $8.6 billion in fiscal 2014 to $37.8 billion in fiscal 2018. Not only is BABA a significant player in China's mobile e-commerce landscape, but it's also getting more into physical retail with supermarkets and grocery delivery. It's also seeing huge growth in international retail, cloud computing, digital media and entertainment, and Ant Financial – an Alibaba affiliate that's risen rapidly to become the most valuable fintech company in the world.","https://www.cryptouniversity.nl/wp-content/uploads/2018/10/alibaba-logo.png"));
        Common.movieList.add(new Movie("Microsoft Corp.","Microsoft has been one of the largest, and arguably best, tech companies in the world since the 1990s. But CEO Satya Nadella, who took the reins from Steve Ballmer in 2014, has revitalized the company, quickly pivoting MSFT into the cloud, where its high-margin Azure computing platform has grown at a torrid pace. The Xbox platform continues to dominate system-based gaming, Bing remains meaningful, the acquired professional network LinkedIn is growing rapidly, and Microsoft's Surface tablet is also thriving. The decision to create a cloud-based Office 365 product (think recurring subscription revenue) has worked brilliantly, and Nadella is positioning Microsoft to be one of the leading AI companies.","https://www.usnews.com/dims4/USNEWS/a948745/2147483647/thumbnail/303x202/quality/85/?url=http%3A%2F%2Fmedia.beam.usnews.com%2Fee%2F87%2Fe6cbcc23489e9302c85648e44ee6%2Fresizes%2F500%2F180525-microsoft-stock.jpg"));
        Common.movieList.add(new Movie("Alphabet (GOOGL, GOOG)","Holding company Alphabet's crown gem is Google, the Mountain View, California-based search giant that's increasingly going head-to-head with Facebook in the duopolistic digital advertising market. Not only is Google the world's most dominant search engine, it's peeling away a larger and larger chunk of marketers' traditional TV ad budgets as YouTube expands. GOOGL is plowing into other growth markets left and right, going after e-commerce with Google Shopping; the mobile economy with its own Google Pixel smartphone and its dominant Android OS; smart devices with Google Home, Nest and other connected devices; and driverless cars, where it's racing forward with self-driving tech and owns a stake in Uber.","https://www.usnews.com/dims4/USNEWS/26e89c3/2147483647/thumbnail/303x202/quality/85/?url=http%3A%2F%2Fmedia.beam.usnews.com%2Fb6%2Fcc%2F6c5c064d48979852eb1f11c78e40%2Fresizes%2F500%2F180525-googlesign-stock.jpg"));
        Common.movieList.add(new Movie(" Amazon" , "Somehow, Amazon.com lived up to the hype. Far from crashing and burning like Pets.com and other casualties of the '90s internet bubble, Amazon thrived, by 2015 crossing $100 billion in revenue. Today, it's truly \"the everything store,\" and despite its size, keeps growing like a weed; revenue is expected to exceed $230 billion in 2018. Amazon's growth levers are astounding. It boasts more than 100 million Prime members (now $119 annually), AWS is the leading cloud computing platform at a run rate topping $21 billion, and Alexa-enabled devices now reach tens of millions of households. The acquisition of Whole Foods also gives Amazon a brick-and-mortar presence – and real-world laboratory." , "http://g-ec2.images-amazon.com/images/G/01/social/api-share/amazon_logo_500500._V323939215_.png"));




    }
}
